compiler_command = "tools/build/cc/ido5.3/cc -w -I. -Iinclude -Iinclude/PR -Iassets -Isrc -D_LANGUAGE_C -D_FINALROM -DVERSION=us -DF3DEX_GBI -D_MIPS_SZLONG=32 -nostdinc -c -G0 -O2 -fno-common -B tools/build/cc/gcc/ -Wuninitialized -Wmissing-braces -Wimplicit -Wredundant-decls -Wstrict-prototypes -DPERMUTER -fforce-addr"
assembler_command = "mips-linux-gnu-as -EB -march=vr4300 -mtune=vr4300 -Iinclude"

[preserve_macros]
"gs?[DS]P.*" = "void"
OVERRIDE_FLAG_CHECK = "int"
OS_K0_TO_PHYSICAL = "int"
"G_.*" = "int"
"TEXEL.*" = "int"
PRIMITIVE = "int"

[decompme.compilers]
"tools/build/cc/gcc/gcc" = "gcc2.8.1"
